### ISSUE TITLE
ios outline

### ISSUE THREAD

**Issue by liyongjie1002** [DlhSoftTeam/Ganttis#1]
Can iOS support outlineGanttChart?

**Comment by DlhSoftTeam** [comment]
Unfortunately not, because there is no "UIOutlineView" in UIKit (iOS – Cocoa Touch), like NSOutlineView in AppKit (macOS – Cocoa). Also, on iPhones the screen size is smaller, so it would be difficult to fit both the hierarchical grid and Gantt chart in the same screen.

The suggestion we have is to use GanttChart component (rather than OutlineGanttChart), and set ganttChartContentController.showsLabels = true (to display task names directly on bars.)

**Comment by Iyongjie** [comment]
We have an iPad scene to use outlineGanttChart，do you have some suggestion？

**Comment by DlhSoftTeam** [comment]
iPadOS is based on iOS, and since the OutlineGanttChart component does use NSOutlineView for its left grid that is not available on iOS, unfortunately it won't be supported on iPads either (unless we'd create and use our own or a third party outline view for iOS). It will work, however, on M1 Macs as they do run macOS, of course.

**Comment by liyongjie1002** [comment]
thank you！
